### ISSUE TITLE
Expected ">" but found "setup"

### ISSUE THREAD

**Issue by helloxm** [slidevjs/slidev#1808] opened 2024-08-09 06:43 UTC
**Environment**

- Slidev version: 0.49.24 and before
- OS: Widows

pnpm build

build error!

infos:

✓ 415 modules transformed.
x Build failed in 1.86s
[vite:esbuild] Transform failed with 1 error:
/node_modules/.pnpm/@slidev+client@0.49.24_@nuxt+kit@3.12.4_rollup@4.20.0__@vue+compiler-sfc@3.4.37_postcss@8.4.4_grj2rorcnuejj5vrm5hzie3tem/node_modules/@slidev/client/internals/SlideLoading.vue?vue&type=script&setup=true&lang.ts:1:8: ERROR: Expected ">" but found "setup"
file:   /node_modules/.pnpm/@slidev+client@0.49.24_@nuxt+kit@3.12.4_rollup@4.20.0__@vue+compiler-sfc@3.4.37_postcss@8.4.4_grj2rorcnuejj5vrm5hzie3tem/node_modules/@slidev/client/internals/SlideLoading.vue?vue&type=script&setup=true&lang.ts:1:8

Expected ">" but found "setup"
1  |  <script setup lang="ts">
   |          ^
2  |  import { onMounted, ref } from 'vue'

**Comment by KermanX** [comment] 2024-08-09 10:29
Cannot be reproduced on my machine. Could you reproduce this in https://sli.dev/new?

**Comment by antfu** [comment] 2024-08-12 09:39
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-12 09:39 UTC
Labels: needs reproduction
