### ISSUE TITLE
Make a bether documentation to usage of icons 

### ISSUE THREAD

**Issue by yodatak** [slidevjs/slidev#1565] opened 2024-05-02 12:56 UTC
Hello, thanks for this awsome product,
I'm not dev and i cannot make it work icons with the documentation, can we add a simple markdown slide to demo the icons ?

**Comment by yodatak** [comment] 2024-05-02 13:00
Exemple i got this error and don't  know how to fix it 
https://github.com/slidevjs/slidev/issues/1148

**Comment by yodatak** [comment] 2024-05-02 13:02
Ok i find why so :
i use vscode and vscode say to run slidev command
This command don't use my packages.json with the icons so it crash 
but if i use pnpm run dev it works 
seem like a dev or chicken egg issue :/

**Comment by antfu** [comment] 2024-05-05 19:20
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-05-05 19:20 UTC
Labels: enhancement
