### ISSUE TITLE
Pressing fullscreen button causes other keystrokes to not be registered

### ISSUE THREAD

**Issue by nojomyth-dev** [slidevjs/slidev#801] opened 2022-12-24 20:29 UTC
**Describe the bug**
After pressing the fullscreen button on the bottom left (where the marker and other utility buttons are) all key presses such as arrow keys and 'F'. It is required to switch tabs or reload the site for the keys to work again.

**To Reproduce**
1. Run: `npm install @slidev/cli @slidev/theme-default`
2. Add any second slide with any content
3. Run: `slidev` within the directory created
4. Open the browser on http://localhost:3030
5. Move the mouse and press the button on the bottom left
6. Try to exit fullscreen mode by pressing 'F' or try to go to the next slide by pressing arrow keys / spacebar

**Desktop (please complete the following information):**
 - OS: Windows 10, latest
 - Browser: Firefox x64 108.0.1
 - Slidev version: latest (v0.38.2)
[minimal_example.zip](https://github.com/slidevjs/slidev/files/10299114/minimal_example.zip)

**Comment by nojomyth-dev** [comment] 2022-12-24 20:51
Also happens on the default example project when using `npm init slidev`

**Comment by tonai** [comment] 2023-01-19 10:15
Can't reproduce on main branch.
This should has been fixed by https://github.com/slidevjs/slidev/pull/832

**Comment by tonai** [comment] 2023-01-24 14:34
Closing this issue as it seems to as been fixed.
Please reopen it if it's not.

**Closed by tonai** 2023-01-24 14:34 UTC
