### ISSUE TITLE
base argument does not work with multiple files build

### ISSUE THREAD

**Issue by yakky** [slidevjs/slidev#1163] opened 2023-10-23 09:08 UTC
**Describe the bug**

running `slidev build *.md --base /<prefix>/` correctly creates a folder for each markdow file, but the base path is the same for each directory an resource loading fails

**To Reproduce**
1. Go to project roon
2. Run `slidev build *.md --base /<prefix>/`
3. Go to dist directory
4. run a simple web server in the dist directory (eg: `python -mhttp.server`)
5. open webserver page on path
6. slides are not shown, 404 errors like `http://localhost:8000/<prefix>/assets/index-b5b9526e.js` are shown in the console

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome / Firefox
 - Slidev version: 0.43.7

**Expected behavior**

The expectation is that the base path for each directory is adapted automatically to `/<prefix>/<slidedeck-name>/`

**Comment by xmusphlkg** [comment] 2024-01-21 03:56
I encountered the same problem, I solved it through for cycleI encountered the same problem, I solved it through for cycle:

`
name: Deploy pages
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - content/*.md
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: |
          npm install
          npm i -D playwright-chromium

      - name: Build presentations
        # run: |
        #   npm run build content/*.md
        #   # remove dist
        #   rm -rf dist
        #   mv content/dist dist
        run: |
          for md_file in content/*.md; do
            # Extract the filename without extension
            filename=$(basename -- "$md_file")
            extension="${filename##*.}"
            filename="${filename%.*}"

            # Run slidev build for each markdown file
            npm run build "$md_file" -- --base /"$filename"/
            # if exist dist/"$filename" folder remove it
            if [ -d dist/"$filename" ]; then
              rm -rf dist/"$filename"
            fi
            mv content/dist dist/"$filename"
          done
`

**Comment by KermanX** [comment] 2024-02-13 03:45
> 2\. Run `slidev build *.md --base /<prefix>/`

How to use glob as entries?🤔 It seems that I can't use glob as entries in the current version.

**Comment by antfu** [comment] 2024-02-13 14:47
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-02-13 14:47 UTC
Labels: needs reproduction
