### ISSUE TITLE
Error reporting using element-plus

### ISSUE THREAD

**Issue by caixunbao** [slidevjs/slidev#900] opened 2023-03-08 08:18 UTC
- OS:window
 - Browser:edge
 - Slidev version:0.40.3

**Error description:**
After installing element-plus, configure the module @slidev/client/main.ts as follows:

import { createApp } from 'vue'
import { createHead } from '@vueuse/head'
import App from './App.vue'
import setupMain from './setup/main'
import { router } from './routes'
import createDirectives from './modules/directives'
import createSlidevContext from './modules/context'
**import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'**
import '/@slidev/styles'
const app = createApp(App)
app.use(router)
**app.use(ElementPlus)**
app.use(createHead())
app.use(createDirectives())
app.use(createSlidevContext())
setupMain({ app, router })
app.mount('#app')

When I run the npm run dev command, the browser reports the following error:

Uncaught SyntaxError: The requested module '/node_modules/dayjs/dayjs.min.js?v=29faa9af' does not provide an export named 'default'

**Comment by antfu** [comment] 2023-03-08 09:27
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-03-08 09:27 UTC
