### ISSUE TITLE
Behavior Change in Public Directory Path Resolution Since @slidev/cli@0.48.0-beta.4

### ISSUE THREAD

**Issue by Ynn** [slidevjs/slidev#1401] opened 2024-03-09 14:29 UTC
I upgraded from @slidev/cli@0.48.0-beta.1 to @slidev/cli@0.48.0-beta.24 and noticed a change in behavior. So, I tested all versions between 1 and 24, and it seems that this change occurred starting from @slidev/cli@0.48.0-beta.4.

Before this change, I could have a slidev directory in which I installed everything, and a subdirectory called slides where I had my folders:

```
slidev
    |-- node_modules
    ... all slidev dependencies & themes
    `-- slides
        |`-- public/images
        | style.css
        | my-slide.md
```

My images and style.css file were found without any problems, and I could even have components in the slides folder that were also found.

Since version @slidev/cli@0.48.0-beta.4, the public folder is no longer mounted from `slidev/slides/public` but from `slidev/public` only. This means I have to move my files there.

This is not convenient for me because I find it much clearer to separate presentations into different folders while keeping the theme and slidev in the main directory.

I also tested version 0.47.5, and it works as I wanted.

I suspect this might be due to one of these changes:
+ Slide route meta  -  by @KermanX in https://github.com/slidevjs/slidev/pull/1315 [(c6e5c)](https://github.com/slidevjs/slidev/commit/c6e5cc08)
+ Package and path resolving - by @KermanX in #1308 (b10d4)

Is this new behavior intended? What can I do to revert to the previous situation?

**Comment by KermanX** [comment] 2024-03-09 14:32
I think this is caused by #1308. In #1308, we assume that the project root is the closest folder with a `package.json`. To use `slidev/slides/public` as the public folder, you can add a `package.json` to `slidev/slides`

**Comment by Ynn** [comment] 2024-03-09 14:44
Thank you for your quick reply :) . What should this minimal package.json contain. Does this mean that I'll have to "pollute" my slides directory with node_modules files on the side?

**Comment by KermanX** [comment] 2024-03-09 14:48
> Thank you for your quick reply :) . What should this minimal package.json contain. Does this mean that I'll have to "pollute" my slides directory with node_modules files on the side?

I think `{ "name": "my-slides", "version": "0.0.0" }` is enough.

**Comment by Ynn** [comment] 2024-03-09 14:52
Thanks for your help. That was what i first try but it does not seems to work.  I have :

```
slidev
    |package.json
    |-- node_modules with all slidev dep & themes
    `-- slides
        |`-- public/images
        | styles.css
        | my-slide.md
        | package.json
```

**Comment by KermanX** [comment] 2024-03-09 14:53
Could you share how you start Slidev dev server?

**Comment by Ynn** [comment] 2024-03-09 14:59
I was using : 

```
npx slidev slides/slide.md --remote
```

but going inside the slide directory and doing : 

```
npx slidev slide.md --remote
```

seems to work. I am not sure why. The only downside is that i have to have a package.json in my slide directory :) 

For the context, i am trying to have all slidev env in a docker env : https://github.com/Ynn/slides.tools . Contrary to what `tangramor /slidev_docker` is doing i setup all the dependencies and modules inside the docker image to avoid having node_modules in my slides directory. I want to have something static as i don't want any surprise when editing or playing my slides.

**Comment by KermanX** [comment] 2024-03-09 15:13
Thank you for pointing this out. I know what the problem is now. Currently, the user root is the closest folder to **cwd** 
 with a `package.json`, which may be not the best solution...

I think there are 3 possible resolving modes.

- Closest package root to **cwd** (Current)
  Pros: If slides are managed in a monorepo, this way gives users the maximum flexibility.
  Cons: This forces users to use monorepo (with a monorepo tool like PNPM) if there are multi slides in one package.
- Closest package root to **slides.md**
  Pros: No need to use a monorepo manager like PNPM, only nested package is required if there are multi slides in one package.
  Cons: Packages nested but not a monorepo is very confused.
- Directory of slides.md (Before #1308)
  Pros: Easy to understand
  Cons: In the future maybe we can build multiple slides together, and this is not very suitable for that.

@antfu, I am not very sure.

**Comment by antfu** [comment] 2024-03-09 17:30
I would prefer to keep the original directory of slides.md approach. Later in the slides.md we could have a 

```md
---
rootDir: ..
---
```

to override that if needed

**Closed** 2024-03-10 13:07 UTC
Labels: help wanted
