### ISSUE TITLE
Safari compatibility issues

### ISSUE THREAD

**Issue by VladVulturescu** [slidevjs/slidev#1570] opened 2024-05-05 13:23 UTC
**Describe the bug**
While browsing the slides of a presentation made with slidev, this caused an interception error with Docusaurus resulting in the index of the page going out off bounds and returning a "Page not found" error. You should go to [this issue](https://github.com/UPB-FILS-MA/upb-fils-ma.github.io/issues/92) to see a more in-depth discussion about the problem.

**To Reproduce**

1. Go to https://embedded-rust-101.wyliodrin.com/docs/lecture/01
2. Browse through any of the lectures at a moderately high speed using the integrated toolbar at the bottom left of the slides until the end (works from beginning to end and vice versa)
3. See the error

**Desktop (please complete the following information):**

- OS: macOS Monterey version 12.3.1
- Browser: Safari
- Slidev version: 0.48.9

**Comment by KermanX** [comment] 2024-05-05 13:32
I am not sure how to fix this. What can Slidev do to prevent this from happening?

**Comment by domnudragota** [comment] 2024-05-05 14:44
Seems to be dependent on the operating system/browser (macOS/Safari). I've tried replicating the bug on Debian -> Firefox browser + Windows 10 -> OperaGx, and I've only managed to replicate it 2 times.

**Comment by KermanX** [comment] 2024-06-15 06:00
Close this because cannot be reproduced stably

**Closed by KermanX** 2024-06-15 06:00 UTC
Labels: needs reproduction
