### ISSUE TITLE
encounter problem with js-yaml

### ISSUE THREAD

**Issue by fjun99** [slidevjs/slidev#1057] opened 2023-07-19 05:49 UTC
when run slidev globally

js-yaml.js:17     GET http://localhost:3030/node_modules/.vite/deps/chunk-6ANHITK6.js?v=f03e0e91 net::ERR_ABORTED 504 (Outdated Optimize Dep)

sometimes: 

chunk-6ANHITK6.js:1     Failed to load resource: the server responded with a status of 504 (Outdated Optimize Dep)

---

chrome error. (after reinstalling, first time ok, then error.)

chrome stealthy mode ok.

microsoft edge ok.

---

tried:

1. reinstall slidev 0.42.5
2. reinstall slidev 0.42.2
2. reinstall js-yaml

thanks.

**Comment by fjun99** [comment] 2023-07-24 02:48
sorry to reopen this issue. 

I reinstalled all and it worked well then.

But the same problem emerges again.

Thanks.

**Comment by antfu** [comment] 2023-09-07 11:19
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-09-07 11:19 UTC
