### ISSUE TITLE
Failed to download repo because browse detects virus

### ISSUE THREAD

**Issue by ronaldosc** [slidevjs/slidev#782] opened 2022-12-01 20:00 UTC
When downloading a copy of the repo in the browser it didn't complete cause of VIRUS detected.

 _- OS: Windows 10 Pro_
 _- Browser: Google Chrome v.107_
 _- Slidev version: none_

**Comment by tonai** [comment] 2023-01-24 11:04
Can you give more information.
Are you using an anti-virus ?

Moreover if you want to get create a slidev project you probably should use `npm init slidev` (see https://sli.dev/).
If you want to get the code of this repository you should probably clone or fork it.
For what purpose do you want to download the  sources ?

**Comment by antfu** [comment] 2023-01-24 12:00
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-01-24 12:00 UTC
