### ISSUE TITLE
docs: howto include icons when publishing

### ISSUE THREAD

**Issue by draptik** [slidevjs/slidev#1558] opened 2024-04-28 22:32 UTC
Can we update the documentation on how to include icons as described in https://sli.dev/guide/syntax#icons when publishing the slides?

I've tried including the packages in the github workflow without success.

```yaml
      - name: Install slidev
        run:  |
            cd ${{ env.PRESENTATION_FOLDER }}
            npm i -g @slidev/cli
            npm i -g @slidev/theme-default
            npm i -g unplugin-icons
            npm i -g @iconify/json
            npm i -g playwright-chromium
```

When presenting the slides on `localhost` everything is fine.

When publishing the slides to github-pages (as an example), the github ci build fails, complaining that 

```txt
✓ 353 modules transformed.
x Build failed in 1.71s
Error: [unplugin-icons] Could not load ~icons/noto/pile-of-poo (imported by ../../../../../../@slidev/slides/57.md): Icon `noto/pile-of-poo` not found
```

I'm probably missing something obvious.

**Comment by antfu** [comment] 2024-04-29 14:23
You can try installing `@iconify-json/note` - otherwise please provide a minimal reproduction

**Comment by antfu** [comment] 2024-04-29 14:23
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-04-29 14:23 UTC
Labels: enhancement

**Comment by draptik** [comment] 2024-04-30 22:24
@antfu thanks for closing this so fast:

It was a 'userland' issue.

In case anybody ends up here:

I hadn't updated my `.github/workflows` script in a while.

Here is  a working example (you need a valid github token):

https://github.com/draptik/slidev-demo1

deploys to

https://github.com/draptik/slidev-demo1-public
