### ISSUE TITLE
Download PDF link is not being shown

### ISSUE THREAD

**Issue by piranna** [slidevjs/slidev#1213] opened 2023-12-09 16:57 UTC
At https://sli.dev/guide/hosting.html#provide-downloadable-pdf it says that by adding `download: true` to the frontmatter, a link to download the PDF version will be shown in the slides, but so far I've been not able to make it work, both with the frontmatter and the CLI option. I've created a new theme project from scratch in case it would be an issue regarding the theme I was using, but with no luck. Reviewing the source code, I've found the responsible fragment at https://github.com/slidevjs/slidev/blob/92d488e1bd8db9ef91388f8a0100a37ac2b36e8d/packages/client/internals/NavControls.vue#L157-L162, not sure if that `configs` (with `s`) is ok or it's a typo, and also i can't be able to see any of the other navigation bar fragments. What I'm doing wrong?

**Comment by KermanX** [comment] 2024-02-12 05:35
Cannot reproduce in v0.47.4. Close this for now.

**Closed by KermanX** 2024-02-12 05:35 UTC
