### ISSUE TITLE
encoding issue when eidt notes in chinese

### ISSUE THREAD

**Issue by zillionare** [slidevjs/slidev#1158] opened 2023-10-15 10:50 UTC
**Describe the bug**
在presenter模式下编辑notes时，有时候文字会在同步之后，变成乱码。

**To Reproduce**
1. 进入presenter模式
2. 编辑中文的notes，此时有概率个别字符会变成乱码

**Desktop (please complete the following information):**
 - OS: macos/ipad
 - Browser: firefox/safari
 - Slidev version: 0.42.5

**Comment by zillionare** [comment] 2023-10-15 11:03
![IMG_F9ED47BA9606-1](https://github.com/slidevjs/slidev/assets/7206696/1c3e157c-08f7-4d9a-bfaa-dad42f7e7e26)

**Comment by antfu** [comment] 2023-10-15 11:19
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-10-15 11:19 UTC
