### ISSUE TITLE
After build -  Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [slidevjs/slidev#1386] opened 2024-03-07 22:25 UTC
**Describe the bug**
Build the slides, open the index with vscode live server and got

<img width="1187" alt="Screenshot 2024-03-07 at 23 25 07" src="https://github.com/slidevjs/slidev/assets/15908060/d03c1bda-2bca-4366-9d51-8a97f49438bd">

Thanks a lot

```
 Cannot read properties of undefined (reading 'data')
```
**To Reproduce**

4. See the error

**Desktop (please complete the following information):**

- OS: mac os
- Browser: brave
- Slidev version: latest

**Comment by antfu** [comment] 2024-03-07 22:31
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by hoeck** [comment] 2024-03-08 01:06
I do have the same issue.

My non working slides are here: https://hoeck.github.io/lightning-talk-runtypes

I did use the `--base` option to be able to deploy to Github pages, see https://github.com/hoeck/lightning-talk-runtypes

Running locally with `npx vite preview --outDir docs --base /lightning-talk-runtypes/` results in the same error, regardless of the browser.

Local devserver and PDF export work fine. Please let me know if you need more help.

**Closed** 2024-03-08 04:53 UTC

**Comment by hoeck** [comment] 2024-03-08 06:29
Hey, thanks for fixing this :heart:
