### ISSUE TITLE
Firefox does not load global-footer.vue

### ISSUE THREAD

**Issue by JamieMair** [slidevjs/slidev#1745] opened 2024-07-09 10:03 UTC
When opening the slides in Firefox (Linux - Ubuntu), the global-bottom.vue global layout is not loaded, works on Brave browser.

**Minimal reproduction**

1. Follow [website docs](https://sli.dev/custom/global-layers)
2. Create `global-bottom.vue` in project root
3. Add some default code:
    ```vue
    <template>
    <footer class="absolute bottom-0 left-0 right-0 p-2">Your Name</footer>
    </template>
    ```
4. Run `npm run dev` and open in Firefox and see no footer on any slides. Does not appear in the DOM either.

**Environment**

- Slidev version: v0.49.3
- Browser: Firefox
- OS: Linux

**Comment by antfu** [comment] 2024-07-10 06:22
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-10 06:22 UTC

**Comment by JamieMair** [comment] 2024-07-10 13:33
Issue fixed itself after restarting the PC
