### ISSUE TITLE
npm init slidev error complaining regarding "shikiji@0.9.14" 

### ISSUE THREAD

**Issue by xu4wang** [slidevjs/slidev#1235] opened 2023-12-29 07:44 UTC
**Describe the bug**

```
 % npm init slidev
Need to install the following packages:
create-slidev@0.46.1
Ok to proceed? (y) 

  ●■▲
  Slidev Creator  v0.46.1

✔ Project name: … slidev
  Scaffolding project in slidev ...
  Done.

✔ Install and start it now? … yes
✔ Choose the agent › npm
npm ERR! code ETARGET
npm ERR! notarget No matching version found for shikiji@0.9.14.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in: /Users/xu4wang/.npm/_logs/2023-12-29T07_34_38_995Z-debug-0.log
Error: Command failed with exit code 1: npm install
    at makeError (file:///Users/xu4wang/.npm/_npx/ce6d27e3bf080801/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///Users/xu4wang/.npm/_npx/ce6d27e3bf080801/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async init (file:///Users/xu4wang/.npm/_npx/ce6d27e3bf080801/node_modules/create-slidev/index.mjs:126:5) {
  shortMessage: 'Command failed with exit code 1: npm install',
  command: 'npm install',
  escapedCommand: 'npm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  cwd: '/Users/xu4wang/Documents/timeslow/website/slidev',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```
**To Reproduce**
1. run `npm init slidev`

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: NA
 - Slidev version: the one chosen by `npm init slidev`

**Comment by xu4wang** [comment] 2023-12-29 07:47
chose pnpm, it shows

```
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for shikiji-transformers@0.9.14

This error happened while installing the dependencies of @slidev/cli@0.46.1
 at shikiji-compat@0.9.14

The latest release of shikiji-transformers is "0.9.13".
```

**Comment by antfu** [comment] 2023-12-29 07:52
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by antfu** [comment] 2023-12-29 07:53
This looks like a npm cache issue to me

**Closed** 2023-12-29 07:53 UTC

**Comment by xu4wang** [comment] 2023-12-29 07:56
> This looks like a npm cache issue to me

Yes.. I fixed it by changing the npm registry, using the official one.

It turn out that taobao mirror is not updated.

```

xuwang@XudeMacBook-Pro blog % pnpm view shikiji-transformers versions
[
  '0.0.0',  '0.7.0-beta.0', '0.7.0-beta.1',
  '0.7.0',  '0.7.1',        '0.7.2',
  '0.7.3',  '0.7.4',        '0.7.5',
  '0.7.6',  '0.8.0',        '0.8.1',
  '0.8.2',  '0.8.3',        '0.8.4',
  '0.8.5',  '0.8.6',        '0.8.7',
  '0.9.0',  '0.9.1',        '0.9.2',
  '0.9.3',  '0.9.4',        '0.9.5',
  '0.9.6',  '0.9.7',        '0.9.8',
  '0.9.9',  '0.9.10',       '0.9.11',
  '0.9.12', '0.9.13'
]
xuwang@XudeMacBook-Pro blog % pnpm config set registry https://registry.npmjs.org/

xuwang@XudeMacBook-Pro blog % pnpm view shikiji-transformers versions             
[
  '0.0.0',  '0.7.0-beta.0', '0.7.0-beta.1',
  '0.7.0',  '0.7.1',        '0.7.2',
  '0.7.3',  '0.7.4',        '0.7.5',
  '0.7.6',  '0.8.0',        '0.8.1',
  '0.8.2',  '0.8.3',        '0.8.4',
  '0.8.5',  '0.8.6',        '0.8.7',
  '0.9.0',  '0.9.1',        '0.9.2',
  '0.9.3',  '0.9.4',        '0.9.5',
  '0.9.6',  '0.9.7',        '0.9.8',
  '0.9.9',  '0.9.10',       '0.9.11',
  '0.9.12', '0.9.13',       '0.9.14'
]
```
