### ISSUE TITLE
Setting embedded style for element animation is always applying scale transition

### ISSUE THREAD

**Issue by george-gca** [slidevjs/slidev#1135] opened 2023-09-20 21:16 UTC
**Describe the bug**
When setting [embedded style](https://sli.dev/guide/syntax.html#embedded-styles) for [element animation](https://sli.dev/guide/animations.html#element-transitions) in slide, it is always applying scale transition.

**To Reproduce**
Create a slide with the given page:

```markdown
---
---

# Animation test

<img
    class="absolute top-25 left-35 w-35 h-35"
    v-click
    src="https://sli.dev/logo-square.png"
/>

<img
    class="absolute top-76 left-35 w-35 h-35"
    v-click
    src="https://sli.dev/logo-circle.png"
/>

<img
    class="absolute top-25 left-95 w-110 h-70"
    v-click
    src="https://sli.dev/logo-triangle.png"
/>

<style>
.slidev-vclick-target {
  transition: opacity 1000ms ease;
}

.slidev-vclick-hidden {
  opacity: 0;
  pointer-events: none;
}
</style>
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Browser: Google Chrome Version 117.0.5938.88 (Official Build) (64-bit)
 - Slidev version: 0.43.5

**Comment by antfu** [comment] 2023-09-21 13:22
I don't understand, what do you expect?

**Comment by george-gca** [comment] 2023-09-21 15:02
To happen an opacity transition and not a scale one, as I set in the `style`.

**Comment by KermanX** [comment] 2024-02-16 10:42
Cannot reproduce in v0.48.0-beta.1. Close this for now.

**Closed by KermanX** 2024-02-16 10:42 UTC
