### ISSUE TITLE
Table of content links keep/steal keyboard focus (mainly with firefox)

### ISSUE THREAD

**Issue by twitwi** [slidevjs/slidev#499] opened 2022-02-27 20:27 UTC
**Describe the bug**
Table of content links keep/steal keyboard focus.

**To Reproduce**
1. Open a presentation containing a `<Toc/>`
2. Click a link in the TOC (a `<RouterLink/>`)
3. Then try to use the keyboard to navigate the presentation

The keys do not navigate anymore in Firefox.
The same is true with chromium but only if the link is to the page itself (I guess that if the element becomes hidden, it is blur()'d in chromium, but not in firefox).

This is somewhat similar in behavior to https://github.com/slidevjs/slidev/issues/495

A solution is to add `@click="$event.target.blur()"` to the `<RouterLink/>` in the implementation of `<TocList/>`.
I'm not sure whether it is too hacky or not. If it is an acceptable solution, **I can PR that**.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Firefox and Chromium (only when remaining on the same page)
 - Slidev version: 0.28.6

**Comment by tonai** [comment] 2022-03-08 08:26
Hello,
I tried to reproduce your problem but didn't find any issue.
I am able to navigate through the slides in Chrome or Firefox without any problem even if my presentation contains a `<toc>` or a `<RouterLink>` component

**Comment by twitwi** [comment] 2022-03-08 10:56
Hi,
Thanks for trying it.

Just to be sure there is no misunderstanding (I'm not sure from your message), the issue occurs when one click on the toc elements (step 2 of the reproduction instruction), before that the navigation works well.

Also, the issue is more problematic with Firefox; with chromium, it is problematic only in a degenerate case.

**Comment by tonai** [comment] 2022-03-10 14:17
Ok I understand.
I asked because I am also working to fix an issue (https://github.com/slidevjs/slidev/pull/513).
Just to inform you that in this PR I created a new Link component, and I updated the `<TocList>` component, so if both PR are approved, we will need to merge them.

**Comment by twitwi** [comment] 2022-03-10 14:35
I think your PR is very important. Fixing the focus (i.e. merging the two) is a very minor work, no worries.

**Comment by tonai** [comment] 2022-04-13 16:28
Can we close this issue ?

**Comment by twitwi** [comment] 2022-04-13 16:52
The issue is still there, but I'll (later) port the fix into the link component to force blur the router links. Thanks to your link component all this will be nicely factorized.

**Closed** 2022-04-14 01:53 UTC
