### ISSUE TITLE
Cannot read properties of undefined (reading 'nav')

### ISSUE THREAD

**Issue by Jason7158** [slidevjs/slidev#672] opened 2022-08-03 00:35 UTC
在slidev中使用$slidev.nav.clicks，比如
```vue
<div v-if="$slidev.nav.clicks <= 3" >
  111
</div>
```
浏览器报错
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'nav')

"dependencies": {
    "@slidev/cli": "^0.35.2",
    "@slidev/theme-apple-basic": "^0.20.0",
    "@slidev/theme-default": "*",
    "@slidev/theme-seriph": "*"
 }

 - OS: Win10专业版 21H2
 - Browser: Microsoft Edge 103.0.1264.77 (正式版本) (64 位)
 - Slidev version:

**Comment by alexanderdavide** [comment] 2022-08-03 16:11
This issue must have been introduced with the latest minor release of v0.35.*.

For the time being, you can pin Slidev to < v0.35. I've tried v0.34.3 successfully.

**Comment by antfu** [comment] 2022-08-03 19:55
Should be fixed in 0.35.4

**Closed by antfu** 2022-08-03 19:55 UTC

**Comment by alexanderdavide** [comment] 2022-08-06 08:52
For me, the error still occurs with v0.35.4. @Jason7158, is it working for you? 

Simple repro that works with a version < 0.35:

```markdown
---
theme: seriph
---

Cannot read properties of undefined (reading 'nav')

<SlideCurrentNo /> / <SlidesTotal />
```

**Comment by Jason7158** [comment] 2022-08-08 00:44
I ended up using V0.35.4.

**Comment by htharoldht** [comment] 2022-08-12 16:48
@alexanderdavide I have this problem too, did you finally solve it?

**Comment by ChiMaoShuPhy** [comment] 2022-08-15 15:04
same issue with latest v0.35.4, it was working properly with previous release of v0.35.4

**Comment by alexanderdavide** [comment] 2022-08-15 15:30
Sadly, I have not, @htharoldht. I am wondering how @Jason7158 now runs on v0.35.4.

@antfu, this issue should probably be reopened.

**Comment by janvorisek** [comment] 2023-06-01 13:14
The issue is still present in `0.41.1`.

{{ $slidev }} is empty
