### ISSUE TITLE
resolve-global breaks with Yarn in windows

### ISSUE THREAD

**Issue by yjl9903** [slidevjs/slidev#403] opened 2021-11-12 19:09 UTC
**Describe the bug**
The package `resolve-global` depends on outdated `global-dir:0.1.1`.

https://github.com/sindresorhus/resolve-global/blob/95cda2b9ca791bac77e9a47366eca1095970cb74/package.json#L35

However, the Yarn global directory has been changed, see https://github.com/sindresorhus/global-dirs/pull/10

**To Reproduce**
1. Install `yarn global add @slidev/cli`
2. Create `slides.md`
3. Run `slidev`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Slidev version: 0.27.10

**Comment by aeudes** [comment] 2021-11-14 11:14
I had a very similar problem on linux with npm if global directory is configured via NPM_CONFIG_PREFIX.

A fix was add in last version of global-dirs with this PR : https://github.com/sindresorhus/global-dirs/pull/7
The update to 1.0.0 is not done in resolve-global due to a release blocker (related to yarn and linux) : https://github.com/sindresorhus/resolve-global/pull/3

As it is not totally the same problem, I can open a dedicated issue but maybe just update the title to track both problem in the same place is better ?

**To Reproduce** Steps to reproduce the behavior:
 
     1. Install `npm install -g @slidev/cli`
 
     2. Create `slides.md`
 
     3. Run `slidev`
 
 
 **Desktop (please complete the following information):**
 
     * OS: Arch linux
 
     * Browser: Firefox
 
     * Slidev version: 0.27.13

**Comment by aeudes** [comment] 2021-11-16 20:55
I can confirm that problem here and #409 are resolved with v0.27.15.

**Closed** 2022-07-08 03:12 UTC
