### ISSUE TITLE
Icons missing in 'npm run export' PDFs

### ISSUE THREAD

**Issue by JPustkuchen** [slidevjs/slidev#1084] opened 2023-08-16 15:10 UTC
**To Reproduce**
Run 
1. `npm init slidev`
2. `npm i -D playwright-chromium`
3. `npm run export`

PDF content page 2:
![grafik](https://github.com/slidevjs/slidev/assets/637807/3890ab4d-7e97-462f-bfe9-29c557eeec2c)

And see this icons broken.

Expected (and acutal running `npm run dev` opened in latest Chrome:
![grafik](https://github.com/slidevjs/slidev/assets/637807/587191c8-760c-4913-9381-37d21bf203a1)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Slidev version: 0.42.8

**Comment by antfu** [comment] 2023-09-07 11:18
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-09-07 11:18 UTC

**Comment by JPustkuchen** [comment] 2023-09-07 11:20
Hi @antfu sorry but I think I provided three simple steps based on the default setup:

Run
>     npm init slidev
>     npm i -D playwright-chromium
>     npm run export
...

So why is this closed?

**Comment by antfu** [comment] 2023-09-07 11:43
I would suggest you try debug it on your side, it might have something to do with windows, chrome, local fonts, or your local playwright setup etc.

As I can't reproduce it (I am on a mac), I don't see a way to help you. Also it's unlikely a Slidev issue (as we just display the emoji, or actually we didn't do anything special to handle them).

**Comment by JPustkuchen** [comment] 2023-09-07 11:47
Thanks for the instant feedback @antfu - but shouldn't we keep it open then at least for other windows users?

I'll ask a teammate to try the same on his Windows 11 machine. FYI: My setup was vanilla, I only installed these tools for Slidev, without modifications, so I'm quite sure I won't be the only one with this problem.

If it happens for all Windows users, perhaps it's at least worth a FAQ entry?

I'll reply here after the test.

**Comment by antfu** [comment] 2023-09-07 11:51
I am sorry that I need to aggressively close issues to keep the maintenance work in control.

I'd be happy to have a FAQ if you find the solution and willing to open a PR adding it.

**Comment by JPustkuchen** [comment] 2023-09-07 11:53
Totally understand, yes. Perhaps GitHub needs an "Ideas" are for this. Discussions also don't seem to be a perfect fit... but yes, not our topic here. Just wanted to say I know that maintainer bias from my Drupal maintainerships.

I'll try to help!

**Comment by JPustkuchen** [comment] 2023-09-07 12:06
Some of these might be related:

- https://github.com/microsoft/playwright/issues/2626
- https://github.com/microsoft/playwright/discussions/11772
- https://bugs.webkit.org/show_bug.cgi?id=214974

**Comment by joshsedl** [comment] 2023-09-07 15:01
Can not reproduce using :
Slidev 0.43.1
Windows 11
WSL2 1.2.3.0

**Comment by JPustkuchen** [comment] 2023-09-07 15:06
I can confirm it's working on @joshsedl's setup, which is quite similar to mine. Like me he ran the steps on WLS2 on Windows 11

I also just tried upgrading to Slidev 0.43.1 with no change. "playwright-chromium": "^1.37.1" is also up to date.

So it must be something locally indeed, perhaps within playwright or its dependencies. I have no clue. If the same should happen to anyone else, please report here.

I'd be really happy to find the deeper reasons. Until I'm the only one reporting this, let's keep this closed. Thank you all!

**Comment by JPustkuchen** [comment] 2023-09-07 15:09
@joshsedl just had the great idea to run
`npx playwright install-deps` once again and you won't believe... NOW IT WORKS! :)

I guess it overwrote / updated something. <3

Hopefully this helps others running into the same situation in the future!
