### ISSUE TITLE
blank webpage

### ISSUE THREAD

**Issue by jneless** [slidevjs/slidev#1239] opened 2024-01-05 08:25 UTC
**Describe the bug**
Hi Slidev, I run the `npx create-slidev` to init a default Slidev with version 0.46.1, via the option of yarn.
but the website is blank.

I try to edit the slides.md, and remove the page of  [# Code], the browser could run.
after a serious of tests, I found the error is the element of   ``` code ``` in the page of [# Code].

Every time, when I remove the ```code``` element, the Slidev worked successfully.  

**To Reproduce**
1. run 'npx create-slidev' in shell
2. select the agent of 'yarn'
3. open localhost:3030
4. See the error: the page is blank
5. remove the ```code``` element in the page of [# code], and other pages
6. it could work

**Desktop (please complete the following information):**
MacOS: 13.3.1
Chip: Apple M1
browser: Microsoft Edge
Slidev Version: v0.46.1

**Comment by antfu** [comment] 2024-02-02 14:35
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-02-02 14:35 UTC
