### ISSUE TITLE
Failed to resolve package "@slidev/theme-seriph/package.json" 

### ISSUE THREAD

**Issue by CoderYuanHub** [slidevjs/slidev#694] opened 2022-08-30 07:08 UTC
全局安装，执行slidev提示
Failed to resolve package "@slidev/theme-seriph/package.json"

**Comment by beierzhijin** [comment] 2022-10-22 06:02
> 全局安装，执行slidev提示 Failed to resolve package "@slidev/theme-seriph/package.json"�

same problem

**Comment by antfu** [comment] 2022-10-22 09:23
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-10-22 09:23 UTC

**Comment by beierzhijin** [comment] 2022-10-22 13:40
> We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
> 
> > [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

你好 我这边的情况就是按照官方的全局安装文档：
第一步： `pnpm add -g @slidev/cli`
第二步： 执行`slidev`，按提示执行就会报 `Failed to resolve package "@slidev/theme-seriph/package.json"`

环境：`windows 11正式版` `Node v16.18.0` `pnpm v7.13.6`
