### ISSUE TITLE
Lots of blank pages when exporting with any format using export.

### ISSUE THREAD

**Issue by zorro430** [slidevjs/slidev#1624] opened 2024-05-29 02:42 UTC
**Describe the bug**
Lots of blank pages when exporting with any format (pptx,md or png ) using export.

<img width="217" alt="image" src="https://github.com/slidevjs/slidev/assets/5017474/e67e2ae0-2aa1-4af1-89c2-ea787d66cd9f">

```
{
  "name": "slidev",
  "type": "module",
  "private": true,
  "scripts": {
    "build": "slidev build",
    "dev": "slidev --remote --bind --open",
    "export": "slidev export"
  },
  "dependencies": {
    "@slidev/cli": "^0.49.4",
    "@slidev/theme-default": "latest",
    "@slidev/theme-seriph": "^0.25.0",
    "mokkapps": "^1.3.0",
    "slidev-theme-hep": "^0.1.1",
    "slidev-theme-light-icons": "^1.0.2",
    "slidev-theme-mokkapps": "^1.3.2",
    "vue": "^3.4.21"
  },
  "devDependencies": {
    "playwright-chromium": "^1.42.1"
  },
  "slidev": {
    "colorSchema": "light" 
  }
}

```

**Desktop (please complete the following information):**

- OS: Mac BigSur 11.6, M1 MacBook Pro
- Browser: Chrome 125.0.6422.112
- Slidev version: 0.49.4

**Comment by KermanX** [comment] 2024-05-29 02:54
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example).
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by KermanX** [comment] 2024-06-03 07:49
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by KermanX** 2024-06-03 07:49 UTC
