### ISSUE TITLE
Export with component

### ISSUE THREAD

**Issue by rightaway** [slidevjs/slidev#1099] opened 2023-08-31 22:58 UTC
Layout is like this

```
project
  dir
    slide.html
  components
    dir
      CompA.vue
```

slide.html uses `<CompA>text</CompA>` and works in dev mode but in export shows just "text" and doesn't use the component.

**Comment by antfu** [comment] 2023-09-07 11:16
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-09-07 11:16 UTC

**Comment by rightaway** [comment] 2023-09-20 18:34
@antfu Please try with any component. Export doesn't use the component.
