### ISSUE TITLE
Can't deploy on Vercel using version v0.37.1 and above

### ISSUE THREAD

**Issue by gquittet** [slidevjs/slidev#886] opened 2023-02-14 19:13 UTC
Unable to deploy on vercel using slidev version v0.37.x and above.

It's working with v0.36.11 and lower.

**Describe the bug**

Stacktrace:

![image](https://user-images.githubusercontent.com/11082739/218834153-0d2443a9-d6bc-4d6d-a00d-b3bb0f9074cb.png)

```
TypeError: `author` must be of type `string`, but was actually of type `boolean`
    at exports.assertIs (/vercel/path0/node_modules/pdf-lib/cjs/utils/validators.js:140:11)
    at PDFDocument.setSubject (/vercel/path0/node_modules/pdf-lib/cjs/api/PDFDocument.js:369:17)
    at genPagePdfOnePiece (/vercel/path0/node_modules/@slidev/cli/dist/export-2BM4EQEA.js:251:11)
    at async exportSlides (/vercel/path0/node_modules/@slidev/cli/dist/export-2BM4EQEA.js:323:5)
    at async build (/vercel/path0/node_modules/@slidev/cli/dist/build-XTITLXMQ.js:740:5)
    at async Object.handler (/vercel/path0/node_modules/@slidev/cli/dist/cli.js:216:5)
Error: Command "npm run build" exited with 1
```

**To Reproduce**
1. Generate a slidev project
2. Deploy it on vercel
4. See the error

**Misc**

I can reproduce the issue with
- Node 16 and 18
- Using NPM and PNPM

**Comment by gquittet** [comment] 2023-02-14 19:16
Because of this commit: https://github.com/slidevjs/slidev/commit/d26139a1410670509d22c55f0684e073934917eb#diff-4fc037dd5180dae1af9ac637aa57f5e164f0dd6119ba0da6681646cee8a1afa6

**Comment by gquittet** [comment] 2023-02-14 19:17
`pdf-lib` seems to be dead and should be replaced.

I will investigate on this issue later.

**Comment by gquittet** [comment] 2023-04-17 07:59
No please stale bot, don't close the issue ;)

**Comment by gquittet** [comment] 2023-06-16 10:10
No please stale bot, don't close the issue ;)

**Comment by antfu** [comment] 2023-06-16 11:20
Sorry for the late response, but we are not able to help without a reproduction.

We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-06-16 11:20 UTC
