### ISSUE TITLE
Failed to resolve import function in script setup ts(in slides.md) 

### ISSUE THREAD

**Issue by mudssky** [slidevjs/slidev#1076] opened 2023-08-10 09:13 UTC
**Describe the bug**

i write a CanvasBoard.vue component
```ts
<template>
  <canvas ref="canvasDom" :width="p.width" :height="p.height">
    当前浏览器不支持canvas元素，请升级或更换浏览器！
  </canvas>
</template>

<script lang="ts" setup>
import { onMounted } from 'vue'
import { ref } from 'vue'
interface Props {
  width?: number
  height?: number
  drawFn?: (ctx: CanvasRenderingContext2D) => void
}
const p = withDefaults(defineProps<Props>(), {
  width: 900,
  height: 450,
  drawFn: undefined,
})

const canvasDom = ref()

onMounted(() => {
  if (p.drawFn) {
    const ctx = canvasDom.value.getContext('2d')
    p.drawFn(ctx)
  }
})
defineExpose({
  canvasDom,
})
</script>

<style lang="scss" scoped>
canvas {
  border: 1px solid #eee;
}
</style>
```
use it in slides.md
```md
<script setup lang="ts">
import {drawTriangle} from './example/examples'
</script>

<CanvasBoard width="200" height="200" :drawFn="drawTriangle"/>
```
See the error
```
17:01:34 [vite] Internal server error: Failed to resolve import "./example/examples" from "..\..\..\..\..\..\..\@slidev\slides\12.md". Does the file exist?
  Plugin: vite:import-analysis
  File: /@slidev/slides/12.md:6:31
  4  |  import InjectedLayout from "/@fs/D:/coding/Projects/frontend/my-slidevs/node_modules/.pnpm/@slidev+client@0.42.5_postcss@8.4.27_vite@4.4.6/node_modules/@slidev/client/layouts/default.vue";
  5  |  import { injectionSlidevContext } from "@slidev/client/constants.ts";
  6  |  import { drawTriangle } from "./example/examples";
     |                                ^
  7  |  const _sfc_main = /* @__PURE__ */ _defineComponent({
  8  |    __name: "12",
      at formatError (file:///D:/coding/Projects/frontend/my-slidevs/node_modules/.pnpm/vite@4.4.6_sass@1.64.1/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:43932:46)
      at TransformContext.error (file:///D:/coding/Projects/frontend/my-slidevs/node_modules/.pnpm/vite@4.4.6_sass@1.64.1/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:43928:19)
      at normalizeUrl (file:///D:/coding/Projects/frontend/my-slidevs/node_modules/.pnpm/vite@4.4.6_sass@1.64.1/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:41746:33)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async file:///D:/coding/Projects/frontend/my-slidevs/node_modules/.pnpm/vite@4.4.6_sass@1.64.1/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:41890:47    
      at async Promise.all (index 5)
      at async TransformContext.transform (file:///D:/coding/Projects/frontend/my-slidevs/node_modules/.pnpm/vite@4.4.6_sass@1.64.1/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:41815:13)
      at async Object.transform (file:///D:/coding/Projects/frontend/my-slidevs/node_modules/.pnpm/vite@4.4.6_sass@1.64.1/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:44222:30)
      at async loadAndTransform (file:///D:/coding/Projects/frontend/my-slidevs/node_modules/.pnpm/vite@4.4.6_sass@1.64.1/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:54878:29)
      at async viteTransformMiddleware (file:///D:/coding/Projects/frontend/my-slidevs/node_modules/.pnpm/vite@4.4.6_sass@1.64.1/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:64266:32)
Failed to resolve import "./example/examples" from "..\..\..\..\..\..\..\@slidev\slides\12.md". Does the file exist?
Failed to resolve import "./example/examples" from "..\..\..\..\..\..\..\@slidev\slides\12.md". Does the file exist? (x2)
```
i use pnpm workspace， my workspace config is below
```yaml
packages:
 - 'projects/slidevs/*'
 - 'packages/*'
```
slides.md path :  my-slidevs\projects\slidevs\learn-canvas\slides.md

**To Reproduce**
4. See the error

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: chrome 114.0.5735.199
 - Slidev version:  "@slidev/cli": "^0.42.5",

**Comment by antfu** [comment] 2023-09-07 11:18
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-09-07 11:18 UTC
