### ISSUE TITLE
Slides shifted to the right in the webapp

### ISSUE THREAD

**Issue by rcalsaverini** [slidevjs/slidev#67] opened 2021-05-11 18:41 UTC
Hello! Great project. I've been using markdown to write beamer slides for years (with `pandoc`) and this is a really nice addition to that space. 

One small issue I've been having is that when I open the web app, my slides seem to be all shifted to the right.

### Steps to reproduce

These are the steps I used:

1. On MacBook pro, open terminal, choose folder, and type `npm init slidev` and follow all standard options. Wait for all packages to be installed.
2. Open Google Chrome and navigate to `http://localhost:3030`.

The slides open like this:
![image](https://user-images.githubusercontent.com/126856/117867073-40e79e80-b26e-11eb-8b8a-15d7c39a4735.png)

![image](https://user-images.githubusercontent.com/126856/117867174-64aae480-b26e-11eb-94e8-89b775e9bd84.png)

**Comment by antfu** [comment] 2021-05-11 19:44
Can't reproduce on my side. Can you check the consoles, and inspect the dom to see what's wrong? Thanks

**Comment by antfu** [comment] 2021-05-11 19:44
Can't reproduce on my side. Can you check the consoles, and inspect the dom to see what's wrong? Thanks

**Comment by nonlinearcom** [comment] 2021-05-11 20:14
Hi, I think it can be solved by removing the width in "slide-content" : 
`<div id="slide-content" style="height: 551.25px; width: 980px;  transform: translate(-50%, -50%) scale(0.694785);">`

**Comment by antfu** [comment] 2021-05-11 20:18
Released in 0.7.4. Would be appreciated if you can help verify if it works.

**Closed as completed** 2021-05-11 20:17 UTC
Labels: needs reproduction

**Comment by kawamataryo** [comment] 2021-05-11 20:26
Thanks. It has been fixed

**Comment by rcalsaverini** [comment] 2021-05-12 17:04
Thanks @antfu! It's 100% fixed on my setup, and working on different screens and resolutions.
