### ISSUE TITLE
Timeout while rendering PDF

### ISSUE THREAD

**Issue by asm0dey** [slidevjs/slidev#865] opened 2023-02-06 12:48 UTC
**Describe the bug**

**To Reproduce**
1. Clone github.com/asm0dey/clean-code-101
2. run `DEBUG=pw:api  pnpm run export-pdf`
3. See something like 

```
❯ DEBUG=pw:api pnpm run export-pdf

> kotlin-spring@ export-pdf /home/finkel/work_self/presentations/clean-code-101
> slidev export --with-clicks --format pdf --output dist/index.pdf



  ●■▲
  Slidev  v0.40.2 

  theme   @slidev/theme-apple-basic
  entry   /home/finkel/work_self/presentations/clean-code-101/slides.md


  pw:api => browserType.launch started +0ms
  pw:api <= browserType.launch succeeded +207ms
  pw:api => browser.newContext started +2ms
  pw:api <= browser.newContext succeeded +700ms
  pw:api => browserContext.newPage started +0ms
  pw:api <= browserContext.newPage succeeded +746ms
  ● rendering...  pw:api => page.goto started +3ms
  pw:api navigating to "http://localhost:12445/print?print=clicks", waiting until "networkidle" +2ms
  pw:api   "commit" event fired +143ms
  pw:api   navigated to "http://localhost:12445/print?print=clicks" +0ms
  ■ rendering...  pw:api   navigated to "http://localhost:12445/print?print=clicks" +417ms
  ▲ rendering...  pw:api   navigated to "http://localhost:12445/print?print=clicks" +124ms
  pw:api   "domcontentloaded" event fired +1ms
  ◆ rendering...  pw:api   "load" event fired +368ms
  ◆ rendering...  pw:api <= page.goto failed +29s
page.goto: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "http://localhost:12445/print?print=clicks", waiting until "networkidle"
============================================================
    at go (/home/finkel/work_self/presentations/clean-code-101/node_modules/.pnpm/@slidev+cli@0.40.2_playwright-chromium@1.30.0/node_modules/@slidev/cli/dist/export-BRPXINGP.js:143:16)
    at genPagePdfOnePiece (/home/finkel/work_self/presentations/clean-code-101/node_modules/.pnpm/@slidev+cli@0.40.2_playwright-chromium@1.30.0/node_modules/@slidev/cli/dist/export-BRPXINGP.js:226:11)
    at genPagePdf (/home/finkel/work_self/presentations/clean-code-101/node_modules/.pnpm/@slidev+cli@0.40.2_playwright-chromium@1.30.0/node_modules/@slidev/cli/dist/export-BRPXINGP.js:290:46)
    at exportSlides (/home/finkel/work_self/presentations/clean-code-101/node_modules/.pnpm/@slidev+cli@0.40.2_playwright-chromium@1.30.0/node_modules/@slidev/cli/dist/export-BRPXINGP.js:319:11)
    at async Object.handler (/home/finkel/work_self/presentations/clean-code-101/node_modules/.pnpm/@slidev+cli@0.40.2_playwright-chromium@1.30.0/node_modules/@slidev/cli/dist/cli.js:331:20) {
  name: 'TimeoutError'
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Desktop (please complete the following information):**
 - OS: `Linux UNIT-1793 5.15.89-1-MANJARO #1 SMP PREEMPT Wed Jan 18 20:37:11 UTC 2023 x86_64 GNU/Linux`
 - Slidev version: `v0.40.2`

**Comment by tonai** [comment] 2023-02-10 14:31
Hello can you to add `css: unocss` in your frontmatter and check if the export still timeout ?

**Comment by asm0dey** [comment] 2023-02-10 15:03
@tonai yes, it works!

**Comment by tonai** [comment] 2023-02-10 15:11
Ok great.
So maybe this your workaround for now.
The issue is cased by windiCSS that triggers a network call to some `@windicss-devtools-update` URL that is not resolved correctly causing the playwright's `waitForLoadState('networkidle')` to never trigger (such causing the timeout).

**Comment by asm0dey** [comment] 2023-02-10 15:14
True, but I have another presentation where I use windicss classes, probably they won't work with uno, right?

**Comment by tonai** [comment] 2023-02-10 15:24
The default unocss configuration is a Tailwind / Windi CSS compact preset, so it should probably be fine.

**Comment by asm0dey** [comment] 2023-02-11 11:20
Oh nice, it works! Should we close this then? Or should I patch something inside the node-modules?

**Comment by tonai** [comment] 2023-02-11 12:20
I think It would still be great to find why it does not work with Windi because it is the default configuration.
But maybe this problem is not related to slidev.
We must dig a little further I think before closing the issue.

**Comment by m0dch3n** [comment] 2023-02-13 09:49
I'm running into the same issue...

While fixing this, we could maybe also add an `opt-out` for unocss/windicss

`css: none` or or we could also maybe add `css: tailwind`

https://github.com/slidevjs/slidev/blob/6dcaa4be07719192b2741525fdfc54f0b925bb79/packages/slidev/node/plugins/preset.ts#L183-L185

In my monorepo I'm using a global tailwind config, which I would prefer to use for the slides too. 

This would prevent me, copying half of the configuration to windi/unocss

**Comment by tonai** [comment] 2023-02-13 10:26
@m0dch3n I would prefer you create another issue for that enhancement, as this is not directly related to the original issue

**Comment by m0dch3n** [comment] 2023-02-13 10:29
yes sure, I'll create a new issue and also a PR for `css: none`

**Comment by m0dch3n** [comment] 2023-02-13 10:39
voila [PR](https://github.com/slidevjs/slidev/pull/881) for #880 is created

**Closed** 2023-02-13 11:15 UTC
