### ISSUE TITLE
click markers scroll entire presenter mode display

### ISSUE THREAD

**Issue by gureckis** [slidevjs/slidev#1781] opened 2024-07-25 05:15 UTC
**Describe the bug**

Click markers automatically scroll the div containing the presenter notes.  However, if there are click down near the bottom of the notes and there's no more room to scroll, slidev is scrolling the entire page.  This obscures the presenter tools and continues onto the next slide.  I attached a video of it happening.

**Minimal reproduction**

https://github.com/user-attachments/assets/139d6e13-df1b-4eb8-865a-6127723e7b64

1. create a slide with presenter notes
2. make the presenter notes long and put a click marker near the end of the note
3. step through the slide in presenter mode
4. notice that click markers near the bottom scroll the entire slide page hiding other elements

I think the best behavior here is to turn off the auto scroll for click markers near the bottom or perhaps more simply just add a padding of space at the bottom of the presenter notes so there is room to scroll the div. 

**Environment**

- Slidev version: 0.49.21
- Browser: ARC
- OS: Mac

**Comment by gureckis** [comment] 2024-07-26 03:05
this suddenly went away for me (but i fixed some other things in a theme), so waiting until i have time to set up a clean test...  otherwise i'll close

**Comment by antfu** [comment] 2024-07-26 10:33
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-26 10:33 UTC
