### ISSUE TITLE
Table of Contents not linkable from exported PDF

### ISSUE THREAD

**Issue by marshallfWCCI** [slidevjs/slidev#1056] opened 2023-07-16 13:11 UTC
If I have a `<Toc>` element at the top of my file, then the resulting headings are clickable in the slideshow.

It would be lovely if they could also be clickable in the exported PDF file.

Thanks for slidev!

**Comment by antfu** [comment] 2023-09-07 11:27
I think they should, can you share a reproduction? Thanks

**Comment by antfu** [comment] 2023-09-07 11:27
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-09-07 11:27 UTC
Labels: enhancement
